development:
  adapter: postgresql
  database: team-18_dev
  host: localhost
  min_messages: warning
  username:

test:
  adapter: postgresql
  database: team-18_test
  host: localhost
  min_messages: warning
  username: